# Generated by Django 4.2.3 on 2023-12-03 20:52

from django.db import migrations, models
import news.validations


class Migration(migrations.Migration):
    dependencies = [
        ("news", "0005_alter_user_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="news",
            name="title",
            field=models.CharField(
                max_length=200, validators=[news.validations.validate_title]
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="name",
            field=models.CharField(max_length=200),
        ),
    ]
